server:
  port: 8000
spring:
  application:
    name: my-zuul-service
#    라우터 역할의 zuul-service
zuul:
  routes:
    first-service:
      path: /first-service/**
      url: http://localhost:8081
    second-service:
      path: /second-service/**
      url: http://localhost:8082
